export const LIST_ARTIST = "LIST_ARTIST";
export const LIST_GENRE = "LIST_GENRE";
export const LIST_ALBUMS_BY_ARTIST = "LIST_ALBUMS_BY_ARTIST";
export const LIST_SONGS_BY_ALBUM = "LIST_SONGS_BY_ALBUM";
export const RANDOM_SONG = "RANDOM_SONG";
export const RESET_SONGS_BY_ALMBUM_LIST = "RESET_SONGS_BY_ALMBUM_LIST";
export const RESET_SONG_RANDOM = "RESET_SONG_RANDOM";

